name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
       # sets up .NET Core SDK 3.1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.101
      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish Example/Example.csproj -c Release -o release --nologo
      # changes the base-tag in index.html from '/' to 'GitBranchUI' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to GitBranchUI
        run: sed -i 's/<base href="\/" \/>/<base href="\/GitBranchUI\/" \/>/g' release/wwwroot/index.html
       # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
      - name: Generate NuGet package
        run: dotnet pack -c Release
      - name: Publish Nuget to GitHub registry
        run: dotnet nuget push ./GitBranchUI/bin/Release/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/y_pyl/index.json --skip-duplicate --no-symbols
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
